// ============================================================
//  結構模板庫  Structure Template Library
//  編劇工作室 Script Studio 的「大腦」：得獎電影最常用的敘事骨架。
//  每個模板都標註「適合的類型與片長」，並附中英對照的節拍說明。
//  你可以自由新增 / 修改這裡的內容，App 會自動讀取。
// ============================================================

// ---- 片長 / 形式（參考山音編劇大師的四種格式）-------------------
const FORMATS = [
  {
    id: 'concept-short',
    name: '概念超短片',
    nameEn: 'Concept Ultra-Short',
    length: '1–3 分鐘',
    desc: '一個強烈的「假如…？」概念 + 一個反轉。適合社群平台、創意短片。',
    recommend: ['pixar-spine', 'kishotenketsu', 'nonlinear'],
  },
  {
    id: 'narrative-short',
    name: '敘事短片',
    nameEn: 'Narrative Short',
    length: '5–10 分鐘',
    desc: '有完整人物弧線的小故事，適合影展與比賽。',
    recommend: ['three-act', 'story-circle', 'kishotenketsu'],
  },
  {
    id: 'feature-commercial',
    name: '商業長片',
    nameEn: 'Commercial Feature',
    length: '90–120 分鐘',
    desc: '強情緒、強節奏、明確類型，追求觀眾沉浸與賣座。',
    recommend: ['save-the-cat', 'three-act', 'heros-journey'],
  },
  {
    id: 'feature-arthouse',
    name: '藝術長片',
    nameEn: 'Arthouse Feature',
    length: '90–120 分鐘',
    desc: '重氛圍、重主題、重情感層次，追求作者性與影展能見度。',
    recommend: ['nonlinear', 'kishotenketsu', 'story-circle'],
  },
  {
    id: 'series',
    name: '多集劇集',
    nameEn: 'Multi-Episode Series',
    length: '每集 20–50 分鐘',
    desc: '以季為單位的長線人物弧線，每集有獨立鉤子又串成主線。',
    recommend: ['save-the-cat', 'heros-journey', 'three-act'],
  },
];

// ---- 類型 Genres ----------------------------------------------
const GENRES = [
  '劇情 Drama', '喜劇 Comedy', '愛情 Romance', '動作 Action',
  '驚悚 Thriller', '恐怖 Horror', '科幻 Sci-Fi', '奇幻 Fantasy',
  '懸疑 Mystery', '犯罪 Crime', '青春 Coming-of-Age', '家庭 Family',
  '歷史 Historical', '音樂 Musical', '紀錄 Documentary', '實驗 Experimental',
];

// ---- 結構模板 Structures --------------------------------------
const STRUCTURES = [
  {
    id: 'three-act',
    name: '三幕劇結構',
    nameEn: 'Three-Act Structure',
    author: '古典戲劇 / Syd Field',
    bestFor: '幾乎所有故事的萬用骨架，新手最好的起點。',
    formats: ['narrative-short', 'feature-commercial', 'feature-arthouse', 'series'],
    examples: ['《教父》', '《阿甘正傳》', '《寄生上流》'],
    summary: '把故事分成「鋪陳 → 衝突 → 解決」三大塊，靠兩個轉折點推進。',
    beats: [
      { name: '第一幕：鋪陳 Setup', desc: '建立主角的日常世界、慾望與缺陷（約前 25%）。' },
      { name: '觸發事件 Inciting Incident', desc: '打破日常的事件，把主角推上旅程。' },
      { name: '第一轉折點 Plot Point 1', desc: '主角下定決心、無法回頭，進入第二幕。' },
      { name: '第二幕：衝突 Confrontation', desc: '層層升高的阻礙與試煉（約中間 50%）。' },
      { name: '中點 Midpoint', desc: '重大翻轉或真相揭露，賭注升級。' },
      { name: '第二轉折點 Plot Point 2', desc: '最低谷，逼出最終對決的決心，進入第三幕。' },
      { name: '第三幕：解決 Resolution', desc: '高潮對決與主題收束（約後 25%）。' },
    ],
  },
  {
    id: 'save-the-cat',
    name: '救貓咪 15 節拍',
    nameEn: 'Save the Cat! Beat Sheet',
    author: 'Blake Snyder',
    bestFor: '商業類型長片，需要精準情緒節奏的賣座片。',
    formats: ['feature-commercial', 'series'],
    examples: ['《全面啟動》', '《淑女鳥》', '《捍衛戰士：獨行俠》'],
    summary: '好萊塢最常用的長片節拍表，把 110 頁劇本切成 15 個情緒節拍。',
    beats: [
      { name: '開場畫面 Opening Image', desc: '第一個鏡頭，定調世界與主角的「之前」狀態。' },
      { name: '主題point出 Theme Stated', desc: '有人說出一句話，暗示全片真正的主題。' },
      { name: '鋪陳 Set-Up', desc: '介紹主角的世界、缺陷與需要被修補的人事物。' },
      { name: '觸發 Catalyst', desc: '改變一切的事件發生（約第 12 頁）。' },
      { name: '掙扎 Debate', desc: '主角猶豫：我該踏出去嗎？' },
      { name: '進入第二幕 Break into Two', desc: '主角主動選擇進入新世界。' },
      { name: 'B 故事 B Story', desc: '通常是愛情或友情線，承載主題。' },
      { name: '玩樂時光 Fun and Games', desc: '兌現「故事前提」的精彩段落，預告片素材都在這。' },
      { name: '中點 Midpoint', desc: '假勝利或假失敗，賭注與時間壓力升級。' },
      { name: '反派逼近 Bad Guys Close In', desc: '內外壓力夾擊，團隊瓦解。' },
      { name: '一無所有 All Is Lost', desc: '最低谷，常伴隨「死亡氣息」。' },
      { name: '靈魂的暗夜 Dark Night of the Soul', desc: '主角在谷底沉澱，準備領悟。' },
      { name: '進入第三幕 Break into Three', desc: '靈光一閃，A 與 B 故事交會，找到解法。' },
      { name: '結局 Finale', desc: '主角運用所學，翻轉局面，打倒反派。' },
      { name: '結尾畫面 Final Image', desc: '與開場畫面呼應，證明主角已徹底改變。' },
    ],
  },
  {
    id: 'heros-journey',
    name: '英雄旅程',
    nameEn: "The Hero's Journey",
    author: 'Joseph Campbell / Christopher Vogler',
    bestFor: '冒險、奇幻、科幻、成長題材的史詩格局。',
    formats: ['feature-commercial', 'series'],
    examples: ['《星際大戰》', '《魔戒》', '《獅子王》'],
    summary: '神話學提煉出的 12 階段旅程，主角從平凡世界走向重生。',
    beats: [
      { name: '平凡世界 Ordinary World', desc: '主角的日常與內在匱乏。' },
      { name: '冒險的召喚 Call to Adventure', desc: '出現一個挑戰或機會。' },
      { name: '拒絕召喚 Refusal of the Call', desc: '恐懼與抗拒。' },
      { name: '遇見導師 Meeting the Mentor', desc: '獲得指引、信心或法寶。' },
      { name: '跨越門檻 Crossing the Threshold', desc: '正式進入非常世界。' },
      { name: '試煉、盟友、敵人 Tests, Allies, Enemies', desc: '學習新世界的規則。' },
      { name: '進逼最深洞穴 Approach the Inmost Cave', desc: '逼近最大的恐懼。' },
      { name: '苦難折磨 Ordeal', desc: '生死交關的核心考驗。' },
      { name: '獎賞 Reward', desc: '取得寶物、知識或和解。' },
      { name: '歸返之路 The Road Back', desc: '帶著代價踏上回程，反派反撲。' },
      { name: '復活 Resurrection', desc: '最終試煉，主角徹底蛻變。' },
      { name: '帶著仙丹歸返 Return with the Elixir', desc: '回到平凡世界，造福他人。' },
    ],
  },
  {
    id: 'story-circle',
    name: 'Dan Harmon 故事圈',
    nameEn: 'The Story Circle',
    author: 'Dan Harmon',
    bestFor: '人物導向的故事、短片、影集單集，八步簡潔有力。',
    formats: ['narrative-short', 'feature-arthouse', 'series', 'concept-short'],
    examples: ['《瑞克與莫蒂》', '《社群網戰》'],
    summary: '把英雄旅程濃縮成一個圓的 8 個步驟，強調「離開舒適圈、付出代價、改變歸來」。',
    beats: [
      { name: '1. 身處舒適圈 You', desc: '主角在熟悉的日常中。' },
      { name: '2. 但渴望某物 Need', desc: '心中有個缺口或慾望。' },
      { name: '3. 進入未知 Go', desc: '跨入不熟悉的情境。' },
      { name: '4. 適應摸索 Search', desc: '在新處境中掙扎、適應。' },
      { name: '5. 找到所求 Find', desc: '得到原本想要的東西。' },
      { name: '6. 付出代價 Take', desc: '為此付出沉重代價。' },
      { name: '7. 帶著改變回歸 Return', desc: '回到原本的世界。' },
      { name: '8. 已然不同 Change', desc: '主角已徹底改變。' },
    ],
  },
  {
    id: 'kishotenketsu',
    name: '起承轉合',
    nameEn: 'Kishōtenketsu',
    author: '東亞古典四幕結構',
    bestFor: '不靠衝突而靠「並置與轉折」的詩意敘事，短片與藝術片的利器。',
    formats: ['concept-short', 'narrative-short', 'feature-arthouse'],
    examples: ['宮崎駿多部作品', '《一一》', '小津安二郎作品'],
    summary: '不依賴主角對抗反派，而是用第三幕的「轉」讓前面的並置產生新意義。',
    beats: [
      { name: '起 Ki（introduction）', desc: '介紹人物與情境。' },
      { name: '承 Shō（development）', desc: '順勢發展，深化日常。' },
      { name: '轉 Ten（twist）', desc: '出現一個看似無關的轉折或新視角——全片的靈魂。' },
      { name: '合 Ketsu（conclusion）', desc: '讓「轉」與前面合流，賦予整體新的意義。' },
    ],
  },
  {
    id: 'pixar-spine',
    name: '皮克斯故事脊椎',
    nameEn: 'Pixar Story Spine',
    author: 'Kenn Adams / Pixar',
    bestFor: '快速抓出故事主幹、概念短片、一句話故事。',
    formats: ['concept-short', 'narrative-short'],
    examples: ['《天外奇蹟》', '《海底總動員》'],
    summary: '用固定句型填空，30 秒抓出一個故事的因果骨幹。',
    beats: [
      { name: '從前從前 Once upon a time…', desc: '建立日常。' },
      { name: '每一天 Every day…', desc: '日常的規律。' },
      { name: '直到有一天 Until one day…', desc: '打破規律的事件。' },
      { name: '因為這樣 Because of that…', desc: '連鎖反應（可重複）。' },
      { name: '因為這樣 Because of that…', desc: '進一步升高。' },
      { name: '直到最後 Until finally…', desc: '高潮與結果。' },
      { name: '從此之後 Ever since then…', desc: '新的日常與主題。' },
    ],
  },
  {
    id: 'nonlinear',
    name: '非線性／多線敘事',
    nameEn: 'Nonlinear / Multi-Strand',
    author: '諾蘭式 / 昆汀式',
    bestFor: '懸疑、燒腦、作者電影，用「敘事順序」本身製造張力與主題。',
    formats: ['feature-arthouse', 'feature-commercial', 'concept-short'],
    examples: ['《記憶拼圖》', '《黑色追緝令》', '《雲圖》', '《敦克爾克》'],
    summary: '故事本體仍有完整因果，但刻意打亂呈現順序（倒敘／多視角／環形／多時空交織）以製造懸念與意義。',
    beats: [
      { name: '核心謎題 The Hook', desc: '先丟出一個結果或謎題，讓觀眾想往回追。' },
      { name: '時間線設計 Timeline Design', desc: '決定打亂方式：倒敘、雙線、環形或多視角。' },
      { name: '錨點 Anchors', desc: '設定讓觀眾不迷路的視覺/聲音/字卡線索。' },
      { name: '交錯揭露 Interweaving', desc: '在不同時間線間切換，每次切換都揭露新資訊。' },
      { name: '匯流點 Convergence', desc: '所有線索在此交會，真相浮現。' },
      { name: '重新理解 Recontextualize', desc: '結局讓觀眾回頭重新理解開場的意義。' },
    ],
  },
  {
    id: 'seven-point',
    name: '七點故事結構',
    nameEn: 'Seven-Point Structure',
    author: 'Dan Wells',
    bestFor: '從結局往回推、確保每個轉折都有對稱呼應的紮實骨架。',
    formats: ['narrative-short', 'feature-commercial', 'feature-arthouse', 'series'],
    examples: ['《星際大戰四部曲》', '《飢餓遊戲》'],
    summary: '先定好「起點」與「終點」的對比，再用兩個轉折、兩個夾擊、一個中點把它連起來。',
    beats: [
      { name: '鉤子 Hook', desc: '主角的起始狀態，與結局形成強烈對比。' },
      { name: '第一轉折 Plot Turn 1', desc: '把主角推進冒險、提出問題。' },
      { name: '第一夾擊 Pinch 1', desc: '施壓，讓反派力量首次現身。' },
      { name: '中點 Midpoint', desc: '主角從被動反應轉為主動出擊。' },
      { name: '第二夾擊 Pinch 2', desc: '更大的打擊，盟友失去、看似全毀。' },
      { name: '第二轉折 Plot Turn 2', desc: '主角取得通往結局的最後一塊拼圖。' },
      { name: '解決 Resolution', desc: '回應開頭的鉤子，完成蛻變。' },
    ],
  },
  {
    id: 'eight-sequence',
    name: '八序列法',
    nameEn: 'Eight-Sequence Approach',
    author: 'Frank Daniel',
    bestFor: '把長片拆成 8 段「迷你電影」，每段都有自己的小目標，最不容易中段崩塌。',
    formats: ['feature-commercial', 'feature-arthouse'],
    examples: ['《虎豹小霸王》', '多數古典好萊塢長片'],
    summary: '一部長片＝8 個各約 10–15 分鐘的序列，每個序列都有自己的張力與小高潮。',
    beats: [
      { name: '序列一：日常與缺口', desc: '建立世界、主角與內在匱乏。' },
      { name: '序列二：觸發與鎖定目標', desc: '事件打破日常，主角立下目標。' },
      { name: '序列三：初次嘗試受挫', desc: '用舊方法解決，失敗。' },
      { name: '序列四：升級，邁向中點', desc: '提高賭注，逼近中點翻轉。' },
      { name: '序列五：中點後的新計畫', desc: '帶著新資訊重新出發。' },
      { name: '序列六：壓力與最低谷', desc: '反派逼近、一無所有。' },
      { name: '序列七：最後一搏的準備', desc: '領悟、集結、決心。' },
      { name: '序列八：高潮與收束', desc: '對決、主題完成。' },
    ],
  },
  {
    id: 'freytag',
    name: '弗萊塔格金字塔',
    nameEn: "Freytag's Pyramid",
    author: 'Gustav Freytag',
    bestFor: '古典悲劇與正劇，重視「上升—高潮—下降」的對稱美感。',
    formats: ['narrative-short', 'feature-arthouse'],
    examples: ['《李爾王》', '古典戲劇'],
    summary: '五段式金字塔：鋪陳上升到高潮，再一路下降到結局。',
    beats: [
      { name: '鋪陳 Exposition', desc: '介紹人物、處境與背景。' },
      { name: '上升動作 Rising Action', desc: '衝突累積、張力升高。' },
      { name: '高潮 Climax', desc: '命運轉捩點，最強烈的一刻。' },
      { name: '下降動作 Falling Action', desc: '高潮的後果連鎖展開。' },
      { name: '結局 Dénouement', desc: '收束、災難或和解。' },
    ],
  },
  {
    id: 'mckee-scene',
    name: '麥基場景設計',
    nameEn: 'McKee Scene/Value',
    author: 'Robert McKee',
    bestFor: '單場戲的打磨：確保每一場都讓某個「價值」發生翻轉，沒有廢戲。',
    formats: ['narrative-short', 'feature-commercial', 'feature-arthouse', 'series'],
    examples: ['《故事》理論', '《唐人街》場景'],
    summary: '每一場戲都要讓一個價值（生/死、愛/恨、自由/受困）從正轉負或負轉正。',
    beats: [
      { name: '開場價值', desc: '這場戲開始時，角色處於正向或負向？' },
      { name: '慾望與衝突', desc: '角色想要什麼？什麼擋住他？' },
      { name: '節拍推進 Beats', desc: '動作與反應一來一往地累積。' },
      { name: '轉折 Turning Point', desc: '一個揭露或行動，扭轉力量關係。' },
      { name: '收場價值', desc: '價值翻到相反極，戲才算「有發生」。' },
    ],
  },
  {
    id: 'romcom',
    name: '浪漫喜劇節拍',
    nameEn: 'Rom-Com Beats',
    author: '類型慣例',
    bestFor: '愛情、喜劇，靠「相遇—相愛—危機—奔向對方」的甜虐節奏。',
    formats: ['feature-commercial', 'narrative-short', 'series'],
    examples: ['《BJ 單身日記》', '《當哈利碰上莎莉》'],
    summary: '從可愛相遇到大誤會分手，再到雨中狂奔的告白。',
    beats: [
      { name: '設定與缺愛', desc: '主角的感情匱乏與錯誤戀愛觀。' },
      { name: '可愛相遇 Meet-Cute', desc: '兩人以有趣方式相遇、互相看不順眼。' },
      { name: '漸生情愫', desc: '相處中卸下心防、火花漸強。' },
      { name: '甜蜜高點', desc: '在一起或差一步，看似圓滿。' },
      { name: '大誤會崩盤', desc: '謊言或恐懼引爆，分手。' },
      { name: '頓悟與奔赴', desc: '主角克服缺陷，奔向對方告白。' },
    ],
  },
  {
    id: 'coming-of-age',
    name: '成長啟蒙結構',
    nameEn: 'Coming-of-Age',
    author: '類型慣例',
    bestFor: '青春、家庭題材，記錄一個人從天真走向成熟的內在蛻變。',
    formats: ['feature-arthouse', 'narrative-short', 'series'],
    examples: ['《淑女鳥》', '《年少時代》', '《站在我這邊》'],
    summary: '透過一段經歷，主角失去天真、認識世界與自己，獲得新的身分。',
    beats: [
      { name: '純真世界', desc: '主角受保護、對世界有美好誤解。' },
      { name: '裂縫出現', desc: '某事讓他第一次看見現實的複雜。' },
      { name: '探索與越界', desc: '嘗試大人的世界，犯錯、受傷。' },
      { name: '幻滅', desc: '失去某個偶像、信念或關係。' },
      { name: '整合', desc: '帶著傷痕接受不完美，長出新的自我。' },
    ],
  },
  {
    id: 'mystery',
    name: '懸疑推理結構',
    nameEn: 'Mystery / Whodunit',
    author: '類型慣例',
    bestFor: '推理、犯罪，靠「謎題—線索—誤導—真相」推著觀眾一起破案。',
    formats: ['feature-commercial', 'feature-arthouse', 'series'],
    examples: ['《控制》', '《尼羅河謀殺案》', '《利刃出鞘》'],
    summary: '先丟出謎團，沿路灑真假線索與紅鯡魚，最後揭曉令人意外又合理的真相。',
    beats: [
      { name: '案件爆發', desc: '罪案或謎團出現，提出核心問題。' },
      { name: '偵查者入場', desc: '主角接手調查，建立規則。' },
      { name: '線索與嫌疑人', desc: '逐一登場，真假交織。' },
      { name: '誤導 Red Herring', desc: '把觀眾帶往錯誤方向。' },
      { name: '黑暗時刻', desc: '線索斷裂或偵查者受威脅。' },
      { name: '真相揭曉', desc: '重組線索，揭露兇手與動機，回看皆有伏筆。' },
    ],
  },
  {
    id: 'horror',
    name: '恐怖片節奏',
    nameEn: 'Horror Structure',
    author: '類型慣例',
    bestFor: '恐怖、驚悚，用「安全—入侵—升級—對抗—餘韻」操控觀眾的恐懼曲線。',
    formats: ['feature-commercial', 'narrative-short'],
    examples: ['《厲陰宅》', '《逃出絕命鎮》', '《宿怨》'],
    summary: '建立日常與規則，讓威脅一步步入侵升級，最後正面對決並留下不安餘韻。',
    beats: [
      { name: '日常與預兆', desc: '正常生活中埋下不祥伏筆。' },
      { name: '第一次異象', desc: '威脅初現，被合理化或忽視。' },
      { name: '規則與升級', desc: '理解威脅的規則，攻擊逐步加劇。' },
      { name: '孤立無援', desc: '求助失敗、人數遞減，退無可退。' },
      { name: '正面對決', desc: '主角反擊，揭開威脅本質。' },
      { name: '不安餘韻', desc: '看似結束，留下未解的恐懼尾巴。' },
    ],
  },
  {
    id: 'revenge',
    name: '復仇結構',
    nameEn: 'Revenge Arc',
    author: '類型慣例',
    bestFor: '動作、犯罪，靠「受害—蛻變—獵殺—代價」的情緒驅動。',
    formats: ['feature-commercial', 'series'],
    examples: ['《追殺比爾》', '《險路勿近》', '《關鍵少數》(變體)'],
    summary: '主角因失去而踏上復仇，過程中逼問「復仇是否值得」。',
    beats: [
      { name: '失去', desc: '重大傷害或剝奪，點燃復仇動機。' },
      { name: '蛻變與準備', desc: '主角脫胎換骨、磨利武器與計畫。' },
      { name: '逐一獵殺', desc: '一個個擊破目標，賭注升高。' },
      { name: '代價浮現', desc: '復仇腐蝕了主角，失去更多。' },
      { name: '最終對決', desc: '面對主謀，完成或放下復仇。' },
      { name: '空洞或救贖', desc: '復仇之後，主角得到什麼、失去什麼。' },
    ],
  },
  {
    id: 'heist',
    name: '劫案計畫結構',
    nameEn: 'Heist Structure',
    author: '類型慣例',
    bestFor: '犯罪、動作，靠「組隊—計畫—執行—翻車—反轉」的精密快感。',
    formats: ['feature-commercial', 'series'],
    examples: ['《瞞天過海》', '《全面啟動》(變體)'],
    summary: '招募團隊、擬定天衣無縫的計畫，執行時意外連連，最後靠隱藏反轉收尾。',
    beats: [
      { name: '誘因與目標', desc: '為何而偷、偷什麼，風險多大。' },
      { name: '組隊', desc: '集結各有專長的成員。' },
      { name: '計畫藍圖', desc: '向觀眾展示理想中的完美流程。' },
      { name: '執行與意外', desc: '實際動手，計畫開始出包。' },
      { name: '翻車危機', desc: '看似全盤皆輸。' },
      { name: '隱藏反轉', desc: '揭露其實早有後手，逆轉成功。' },
    ],
  },
  {
    id: 'rashomon',
    name: '羅生門多視角',
    nameEn: 'Rashomon / Multiple POV',
    author: '黑澤明',
    bestFor: '探討「真相的相對性」，同一事件用不同人視角各說各話。',
    formats: ['feature-arthouse', 'narrative-short'],
    examples: ['《羅生門》', '《最後的決鬥》'],
    summary: '同一事件被多個角色各自重述，版本互相矛盾，逼觀眾思考何謂真相。',
    beats: [
      { name: '事件框架', desc: '先給出事件結果與懸念。' },
      { name: '版本一', desc: '第一位當事人的主觀敘述。' },
      { name: '版本二', desc: '第二位當事人，細節開始矛盾。' },
      { name: '版本三（以上）', desc: '更多視角，真相更模糊。' },
      { name: '並置與留白', desc: '不給標準答案，呈現人性與記憶的不可靠。' },
    ],
  },
  {
    id: 'frame-story',
    name: '框架故事',
    nameEn: 'Frame Story',
    author: '古典敘事',
    bestFor: '用「現在的敘述者」包住「過去的主線」，增加層次與懸念。',
    formats: ['feature-arthouse', 'feature-commercial', 'series'],
    examples: ['《鐵達尼號》', '《大智若魚》', '《一千零一夜》'],
    summary: '一個外層故事（誰在說、為何說）包裹住內層的主要故事。',
    beats: [
      { name: '外層開場', desc: '現在的敘述者與聆聽者，提出疑問。' },
      { name: '進入內層', desc: '回到過去，展開主線故事。' },
      { name: '內層發展', desc: '主線完整推進。' },
      { name: '回到外層', desc: '不時切回現在，產生對照與評論。' },
      { name: '雙層收束', desc: '內層真相回扣外層，敘述者也被改變。' },
    ],
  },
  {
    id: 'dual-timeline',
    name: '雙時間線交錯',
    nameEn: 'Dual Timeline',
    author: '現代敘事',
    bestFor: '讓「過去」與「現在」互相解釋，謎底隨交錯逐步浮現。',
    formats: ['feature-arthouse', 'feature-commercial', 'series'],
    examples: ['《控制》', '《雲端情人》(變體)', '《我們》'],
    summary: '兩條時間線平行剪輯，彼此呼應，最終在交會點揭露關鍵真相。',
    beats: [
      { name: '雙線並置開場', desc: '同時建立過去線與現在線的鉤子。' },
      { name: '交替推進', desc: '兩線輪流前進，每次切換都揭露一點。' },
      { name: '鏡像呼應', desc: '兩線出現呼應的畫面或主題。' },
      { name: '真相交會', desc: '過去解釋了現在的謎團。' },
      { name: '合流收束', desc: '兩線在情感或事件上匯合作結。' },
    ],
  },
  {
    id: 'in-medias-res',
    name: '從中段開始',
    nameEn: 'In Medias Res',
    author: '古典技巧',
    bestFor: '一開場就把觀眾丟進高張力時刻，再回頭交代來龍去脈。',
    formats: ['feature-commercial', 'narrative-short', 'concept-short'],
    examples: ['《全面啟動》', '《瘋狂麥斯：憤怒道》(變體)'],
    summary: '故事從劇情中段的緊張點切入，之後再倒敘補完前情。',
    beats: [
      { name: '高張力切入', desc: '直接從危機或謎團的中段開場。' },
      { name: '懸念鎖定', desc: '丟出「他怎麼會走到這步？」的疑問。' },
      { name: '回溯補完', desc: '倒回起點，交代事件如何形成。' },
      { name: '追上現在', desc: '時間線追回開場那一刻。' },
      { name: '超越與收束', desc: '越過開場點，給出結局與意義。' },
    ],
  },
  {
    id: 'circular',
    name: '環形結構',
    nameEn: 'Circular / Bookend',
    author: '現代敘事',
    bestFor: '首尾呼應、命運循環，結尾回到開場但意義已完全不同。',
    formats: ['feature-arthouse', 'narrative-short', 'concept-short'],
    examples: ['《險路勿近》', '《2001 太空漫遊》(變體)'],
    summary: '結尾回到與開場相同的畫面或情境，但觀眾的理解已被整部片改寫。',
    beats: [
      { name: '開場意象', desc: '一個之後會重現的畫面或情境。' },
      { name: '展開旅程', desc: '主線故事推進與轉變。' },
      { name: '累積意義', desc: '事件為開場意象灌注新含義。' },
      { name: '回到原點', desc: '重現開場畫面。' },
      { name: '意義翻轉', desc: '同樣的畫面，現在代表全然不同的東西。' },
    ],
  },
  {
    id: 'road-movie',
    name: '公路電影結構',
    nameEn: 'Road Movie',
    author: '類型慣例',
    bestFor: '旅程即成長：一段移動把外在地理變成內在轉變。',
    formats: ['feature-arthouse', 'feature-commercial'],
    examples: ['《末路狂花》', '《陽光小小姐》', '《關於施密特》'],
    summary: '主角踏上一段旅程，沿途的人事物推動他面對自己、產生改變。',
    beats: [
      { name: '出發的理由', desc: '逃離或追尋，踏上旅途。' },
      { name: '上路', desc: '離開熟悉世界，進入未知。' },
      { name: '途中相遇', desc: '一連串人事物，像試煉也像鏡子。' },
      { name: '中途危機', desc: '旅程受阻、關係緊張或迷失方向。' },
      { name: '抵達或轉向', desc: '終點未必是目的地，內在已轉變。' },
    ],
  },
  {
    id: 'hyperlink',
    name: '多線交織',
    nameEn: 'Hyperlink / Ensemble',
    author: '現代敘事',
    bestFor: '群像電影，多組看似無關的人物，最後因一件事交會。',
    formats: ['feature-arthouse', 'feature-commercial', 'series'],
    examples: ['《衝擊效應》', '《愛是您愛是我》', '《心靈角落》'],
    summary: '多條獨立支線平行推進，靠主題或一個事件把所有人連在一起。',
    beats: [
      { name: '多線開場', desc: '分別介紹數組人物與各自的處境。' },
      { name: '平行推進', desc: '各線獨立發展，暗藏共同主題。' },
      { name: '線索交叉', desc: '人物開始彼此擦身、間接影響。' },
      { name: '匯流事件', desc: '一個關鍵事件把所有線拉到一起。' },
      { name: '主題收束', desc: '所有支線共同照亮一個主題。' },
    ],
  },
  {
    id: 'kdrama',
    name: '韓劇 16 集結構',
    nameEn: 'K-Drama 16-Ep',
    author: '韓劇產業慣例',
    bestFor: '週更連續劇，每集結尾都要有讓人追下去的鉤子。',
    formats: ['series'],
    examples: ['《鬼怪》', '《愛的迫降》', '《我的大叔》'],
    summary: '以 16 集為一季，前段建立關係與設定，中段甜蜜與誤會，後段危機與大結局。',
    beats: [
      { name: '第 1–2 集：相遇設定', desc: '主角群登場、命運相遇、立下核心懸念。' },
      { name: '第 3–6 集：關係升溫', desc: '情感與任務線交織推進。' },
      { name: '第 7–8 集：中段反轉', desc: '揭露身世或祕密，關係翻轉。' },
      { name: '第 9–12 集：甜蜜與陰影', desc: '高甜同時反派/命運步步逼近。' },
      { name: '第 13–14 集：最大危機', desc: '生離死別、誤會爆發、看似無解。' },
      { name: '第 15–16 集：解結與收束', desc: '化解危機、情感圓滿或留白。' },
    ],
  },
  {
    id: 'short-drama-vertical',
    name: '豎屏短劇結構',
    nameEn: 'Vertical Micro-Drama',
    author: '短劇產業慣例',
    bestFor: '手機豎屏微短劇，每集 1–2 分鐘，靠強鉤子與卡點留人。',
    formats: ['series', 'concept-short'],
    examples: ['各大短劇平台爆款'],
    summary: '黃金三秒抓住人，每集一個爽點或打臉，結尾卡在最揪心處。',
    beats: [
      { name: '黃金三秒', desc: '開頭三秒拋出衝突或反差，勾住手指。' },
      { name: '快速設定', desc: '幾句話交代人物關係與處境。' },
      { name: '爽點/打臉', desc: '每集至少一個逆襲、打臉或反轉。' },
      { name: '情緒拉滿', desc: '誤會、虐心或霸總名場面堆疊。' },
      { name: '卡點收尾', desc: '在最揪心或最爽的前一刻斷掉，逼人看下一集。' },
    ],
  },
  {
    id: 'mv-visual',
    name: 'MV 視覺敘事結構',
    nameEn: 'Music Video Narrative',
    author: '影像音樂慣例',
    bestFor: '音樂錄影帶、短片視覺敘事，跟著歌曲段落起伏鋪排情緒與意象。',
    formats: ['concept-short', 'narrative-short'],
    examples: ['多數敘事型 K-pop／流行 MV'],
    summary: '依歌曲結構（前奏、主歌、副歌、橋段、最後副歌）對應視覺情緒的層層堆疊與爆發。',
    beats: [
      { name: '前奏：氛圍建立', desc: '一個強烈開場意象，定調世界與情緒。' },
      { name: '主歌：鋪陳', desc: '帶出人物與處境，情緒緩緩累積。' },
      { name: '副歌：第一次爆發', desc: '視覺與情緒第一次拉到高點。' },
      { name: '第二段：擴張', desc: '加入變奏、新場景或衝突。' },
      { name: '橋段：轉折', desc: '節奏轉變，情緒最深或最痛的一刻。' },
      { name: '最後副歌：總爆發', desc: '所有意象匯聚，視覺高潮與餘韻。' },
    ],
  },
  {
    id: 'tragedy',
    name: '悲劇結構',
    nameEn: 'Classical Tragedy',
    author: '亞里斯多德',
    bestFor: '探討命運與性格缺陷如何把人推向毀滅。',
    formats: ['feature-arthouse', 'narrative-short'],
    examples: ['《伊底帕斯王》', '《黑天鵝》', '《教父 2》(麥可線)'],
    summary: '高位的主角因致命缺陷（hubris）做出選擇，一步步走向不可逆的毀滅與領悟。',
    beats: [
      { name: '高處的主角', desc: '主角擁有地位或才華，藏著致命缺陷。' },
      { name: '致命選擇', desc: '因傲慢或執念做出關鍵決定。' },
      { name: '上升的假象', desc: '看似得到想要的，實則埋下禍根。' },
      { name: '逆轉 Peripeteia', desc: '情勢急轉直下，控制權喪失。' },
      { name: '醒悟 Anagnorisis', desc: '太遲地看清真相與自己的責任。' },
      { name: '毀滅與淨化', desc: '走向悲劇結局，觀眾獲得情感淨化。' },
    ],
  },
  {
    id: 'abt',
    name: 'ABT 三段敘事',
    nameEn: 'And–But–Therefore',
    author: 'Randy Olson',
    bestFor: '一句話／一段預告／提案，用最精簡的因果說清楚一個故事。',
    formats: ['concept-short', 'narrative-short', 'feature-commercial', 'series'],
    examples: ['多數高概念 logline 與預告'],
    summary: '用「然後（And）建立、但是（But）製造衝突、所以（Therefore）導出結果」三段把故事說清楚。',
    beats: [
      { name: '然後 And（設定）', desc: '建立日常與背景，事情本來是這樣。' },
      { name: '但是 But（衝突）', desc: '出現一個打破平衡的問題或對立。' },
      { name: '所以 Therefore（結果）', desc: '主角因此採取行動，導向結局。' },
    ],
  },
  {
    id: 'noir',
    name: '黑色電影結構',
    nameEn: 'Film Noir',
    author: '類型慣例',
    bestFor: '硬漢偵探、宿命氛圍，主角越查越深、被慾望與背叛拖入深淵。',
    formats: ['feature-arthouse', 'feature-commercial'],
    examples: ['《唐人街》', '《雙重保險》', '《銀翼殺手》(變體)'],
    summary: '一樁委託把憤世的主角捲入腐敗網絡，蛇蠍美人與背叛讓他走向宿命結局。',
    beats: [
      { name: '委託上門', desc: '一個案子或女人找上憤世的主角。' },
      { name: '越陷越深', desc: '調查揭開更大的腐敗與謊言。' },
      { name: '致命誘惑', desc: '蛇蠍美人或慾望模糊了是非。' },
      { name: '背叛與真相', desc: '盟友翻臉，真相比想像黑暗。' },
      { name: '宿命結局', desc: '主角付出代價，正義灰暗或落空。' },
    ],
  },
  {
    id: 'disaster',
    name: '災難片結構',
    nameEn: 'Disaster Movie',
    author: '類型慣例',
    bestFor: '災難、動作，靠「預警—爆發—逃生—犧牲—餘生」的群體求生張力。',
    formats: ['feature-commercial'],
    examples: ['《鐵達尼號》', '《2012》', '《機艙》'],
    summary: '建立人物與被忽視的預警，災難全面爆發，眾人逃生、犧牲，少數倖存。',
    beats: [
      { name: '日常與預警', desc: '介紹群像人物，專家警告卻被忽視。' },
      { name: '初次徵兆', desc: '小規模災害出現，眾人半信半疑。' },
      { name: '全面爆發', desc: '災難大規模降臨，秩序崩潰。' },
      { name: '逃生與抉擇', desc: '人物各自求生，道德與親情受考驗。' },
      { name: '犧牲', desc: '有人為他人而死，情感高潮。' },
      { name: '餘生與重建', desc: '倖存者走出廢墟，帶著創傷與希望。' },
    ],
  },
  {
    id: 'kubler-ross',
    name: '五階段情緒弧',
    nameEn: 'Five Stages of Grief',
    author: 'Kübler-Ross',
    bestFor: '處理失去、創傷與和解的角色內在旅程，情感片利器。',
    formats: ['feature-arthouse', 'narrative-short', 'series'],
    examples: ['《海邊的曼徹斯特》', '《分居風暴》(變體)'],
    summary: '主角面對重大失去，依否認、憤怒、討價還價、沮喪、接受的情緒曲線前進。',
    beats: [
      { name: '否認', desc: '拒絕接受已發生的失去，麻木或逃避。' },
      { name: '憤怒', desc: '把痛苦轉成對他人或自己的怒火。' },
      { name: '討價還價', desc: '試圖用各種方式換回失去的東西。' },
      { name: '沮喪', desc: '墜入低谷，承認無力與空洞。' },
      { name: '接受', desc: '與失去和解，找到帶傷前行的方式。' },
    ],
  },
  {
    id: 'survival',
    name: '生存電影結構',
    nameEn: 'Survival Structure',
    author: '類型慣例',
    bestFor: '單人或小團體在極端環境求生，靠「困境—適應—絕境—自救」推進。',
    formats: ['feature-commercial', 'feature-arthouse', 'narrative-short'],
    examples: ['《絕地救援》', '《一切始於塔斯馬尼亞》(變體)', '《127 小時》'],
    summary: '主角被困於致命環境，從崩潰到學會生存，在絕境中做出最後自救。',
    beats: [
      { name: '陷入困境', desc: '災變把主角丟進孤立的致命處境。' },
      { name: '盤點與崩潰', desc: '評估資源，恐懼與絕望第一次襲來。' },
      { name: '適應求生', desc: '建立日常、解決一個個生存問題。' },
      { name: '希望破滅', desc: '逃生計畫受挫，撐到極限。' },
      { name: '孤注一擲', desc: '用盡一切做最後自救。' },
      { name: '獲救或超脫', desc: '生還，或在精神上獲得救贖。' },
    ],
  },
  {
    id: 'sports-underdog',
    name: '運動逆襲結構',
    nameEn: 'Underdog / Sports',
    author: '類型慣例',
    bestFor: '勵志、運動，魯蛇透過苦練與團隊，在最終賽事證明自己。',
    formats: ['feature-commercial', 'series'],
    examples: ['《洛基》', '《卡特教練》', '《攻其不備》'],
    summary: '不被看好的主角遇見導師、苦練成長，歷經挫敗，在大賽中發光（未必奪冠，但已超越自己）。',
    beats: [
      { name: '魯蛇處境', desc: '主角被輕視、自我懷疑。' },
      { name: '召喚與導師', desc: '機會降臨，遇見嚴厲教練或夥伴。' },
      { name: '苦練蒙太奇', desc: '艱苦訓練，能力與信心成長。' },
      { name: '首勝與自滿', desc: '初嘗勝利，卻因驕傲或意外受挫。' },
      { name: '最低谷', desc: '重大失敗、傷病或團隊分裂。' },
      { name: '最終賽事', desc: '大賽決戰，超越自我，雖敗猶榮或逆轉奪冠。' },
    ],
  },
  {
    id: 'monster',
    name: '怪獸電影結構',
    nameEn: 'Monster / Creature',
    author: '類型慣例',
    bestFor: '科幻、恐怖，靠「徵兆—現身—失控—弱點—決戰」操控未知的恐懼。',
    formats: ['feature-commercial'],
    examples: ['《大白鯊》', '《異形》', '《哥吉拉》'],
    summary: '怪獸先以徵兆暗示存在，逐步現身肆虐，人類找出弱點後正面決戰。',
    beats: [
      { name: '徵兆', desc: '不明攻擊或痕跡，怪獸只聞其聲。' },
      { name: '首次現身', desc: '怪獸正式登場，造成第一波傷亡。' },
      { name: '低估與失控', desc: '人類應對失敗，威脅全面失控。' },
      { name: '研究弱點', desc: '理解怪獸的本質與致命弱點。' },
      { name: '正面決戰', desc: '集中火力於弱點，殊死一搏。' },
      { name: '餘波', desc: '擊退之後，留下未必終結的暗示。' },
    ],
  },
];

module.exports = { FORMATS, GENRES, STRUCTURES };
